name: linux build and tests (1)

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: olafurpg/setup-scala@v10

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 8
        cache: "maven"

    - name: runforce-checkout
      uses: actions/checkout@v2
      with:
        repository: nawforce/runforce
        path: './runforce'

    - name: runforce-compile
      working-directory: './runforce'
      run: mvn -B install -Dgpg.skip

    - name: Build with Maven
      run: |
        mvn --version
        mvn -B install -Dgpg.skip

    - uses: actions/upload-artifact@v2
      with:
        name: dependencies
        path: ./apexlink/target/dependency/

    - uses: actions/upload-artifact@v2
      with:
        name: apexlink
        path: ./apexlink/target/apexlink.jar

  test_java_8:
    needs: build
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "8"    

