name: linux build and tests 

# linux build and tests for java versions 8 and 11

on:
  workflow_dispatch:

jobs:
  linux_build_java_8:
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  linux_test_java_8:
    needs: linux_build_java_8
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  linux_build_java_11:
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      java_version: "11"    
      dependencies_name: "linux_java_11_deps"
      artifact_name: "linux_java_11"

  linux_test_java_11:
    needs: linux_build_java_11
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "11"    
      dependencies_name: "linux_java_11_deps"
      artifact_name: "linux_java_11"
