name: linux build and tests 

on:
  workflow_dispatch:

jobs:
  build_java_8:
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  test_java_8:
    needs: build_java_8
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "8"    
      dependencies_name: "linux_java_8_deps"
      artifact_name: "linux_java_8"

  build_java_11:
    uses: ./.github/workflows/reusable_linux_build.yml
    with:
      java_version: "11"    
      dependencies_name: "linux_java_11_deps"
      artifact_name: "linux_java_11"

  test_java_11:
    needs: build_java_11
    uses: ./.github/workflows/reusable_tests.yml
    with:
      agent: "ubuntu-latest"
      java_version: "11"    
      dependencies_name: "linux_java_11_deps"
      artifact_name: "linux_java_11"
