name: resuable tests

on:
  workflow_call:
    inputs:
      agent:
        description: 'Agent to run on'
        required: true
        type: string
      java_version:
        description: 'Java version to install'
        required: true
        type: string
      dependencies_name:
        description: 'Name for dependencies artifact'
        required: true
        type: string
      artifact_name:
        description: 'Name for apexlink artifact'
        required: true
        type: string

jobs:
  tests:
    runs-on: ${{ inputs.agent }}

    steps:

    - name: Set up java
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: ${{ inputs.java_version }}

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.dependencies_name }}
        path: ./artifacts/dependencies

    - uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact_name }}
        path: ./artifacts

    - name: display build
      run: ls -l ./artifacts

    - name: display java version
      run: java -version

    - name: TriggerX
      run: java -cp "./artifacts/dependencies/*:./artifacts/apexlink.jar" com.nawforce.apexlink.ApexLink -verbose samples/TriggerX/TriggerX

